### ISSUE TITLE
Error handling with get() function

### ISSUE THREAD

**Issue by LucAngevare** [TomPrograms/stormdb#18]
To the best of my knowledge, there is currently no error handler for when a key does not exist. The current implementation is not only unreliable as you risk accidentally adding keys to the object when attempting to call the value of a non-existing key, but also somewhat annoying when trying to implement a function to check if a user already has already used the command before writing to the database with a default starting value.

This function fairly easy to implement because JavaScript has it's own function to check if an object has a key; `Object.hasOwnProperty(key)`, which returns `true` if it exists and `false` if it doesn't. In this example you'd just need to write the following, I'll add a pull request.

```js
  get(value) {
    if (Object.hasOwnProperty(value)) {
        let clone = Object.assign(Object.create(Object.getPrototypeOf(this)), this);
        clone.pointers = [...clone.pointers, value];
        return clone;
    } else {
        throw new Error("Key does not exist.");
  }
```

**Comment by TomPrograms** [comment]
Hi, thanks for the issue and the pull request. 

I'll have to decline on this update, as the current design is intentional. Consider this scenario, we start with an empty database, and then run the line `db.get("a").get("b").set("c");`. The intentional and current behaviour is the database state will become:

```json
{
    "a": {
        "b": "c"
    }
}
```

If we precede with the changes, the keys "a", "b" will no longer be able to be added to the pointers list, and therefore this behaviour will no longer work. Therefore, I will decline the changes at this moment in time. You can see this functionality work [here](https://tomprograms.github.io/stormdb/?code=%2F%2F%2520clear%2520default%2520database%250Adb.state%2520%3D%2520%257B%257D%3B%250AupdateDatabaseState%28%29%3B%250A%250A%2F%2F%2520code%250Adb.get%28%2522a%2522%29.get%28%2522b%2522%29.set%28%2522c%2522%29%3B). When you click run, the database will be cleared and then the line above will be executed. Thanks for your time and contribution.

**Comment by LucAngevare** [comment]
That actually makes perfect sense, thanks for clearing that one up. In this case I don't see a (clear-cut) way of making this functionality possible, I might take another look at your code inside the `value()` function though, there might be a way to implement this into that while keeping all the currently (well) designed features. I do agree that the current designed functionality would be a shame to put away for an error handler. Thanks so much for your input and time!

**Comment by TomPrograms** [comment]
No problem. Have a good one.

**Comment by TomPrograms** [comment]
@LucAngevare after some thought I added [this commit](https://github.com/TomPrograms/stormdb/commit/c19febadc2e06685effaaea5c292e65fffc43811). My logic was if we have an empty database, and we try `db.get("test").value()` it should return `undefined` as that is how it would work on a normal JSON object (`emptyJSONObj[`test`] === undefined`), however if we `db.get("test").get("test").value()` on an empty database it should through an error, as that is how it would work on a normal JSON object (emptyJSONObj["test"]["test"] would throw an error). Thanks a lot for the thoughts and inspiration.

**Comment by LucAngevare** [comment]
Oh that's awesome, that's exactly what I had in mind. Thanks for the extra thought and I'm honestly glad I could be of any help at all.
