### ISSUE TITLE
Database not reading the JSON file and returning outdated value

### ISSUE THREAD

**Issue by MCUniversity** [TomPrograms/stormdb#21]
Sometimes the database returns an outdated value. 
I have multiple files inside one node.js project. Different files are run depending on what is happening. One file only loads the value from the database, and another loads it and then updates it. Lets call them file 1 and 2.
When I run file 2 to update the value in the database it reads the correct value and saves it successfully. When I then run file 1 to read the value it reads the correct value.
But when I first run file 1 to check the value, then file 2 to update it and then again file 1 to check if it updated correctly, it returns me the outdated number that I got when I first checked the value before updating it, even though I can clearly see that the value got updated correctly when I read the JSON file in a text editor.

**Comment by TomPrograms** [comment]
I think the best way to try and fix this is to have one central file that you use for database management - let's call it `database.js`. Inside database.js you'll have something like:

```js
// stormdb setup etc.

module.exports = db;
```

And then in each file - 1 and 2 - import database.js instead of stormdb directly, as then database.js should share one state between files. Let me know if this works for you.

**Comment by MCUniversity** [comment]
Sorry, I forgot to reply to this. Yes, what you suggested fixed the issue, thanks.
