### ISSUE TITLE
QUESTION: Size limits on DB

### ISSUE THREAD

**Issue by JamesBotterill** [TomPrograms/stormdb#34]
I wondered if there's been any stress tests on the max size for a db before performance is impacted?

I've built a small web app using StormDB and I'm wondering on scalability and when I might need to migrate to another db.

**Comment by TomPrograms** [comment]
I don't have any stress tests, but you're right that if you're dealing with millions of entries or 100s of megabytes of data you should probably migrate to a different database.

The main problem will come when writing large amounts of data to a file or loading it from a file, which will bottleneck with large amounts of data. Otherwise the data will be in primary memory and again if there is gigabytes of data this could cause a problem.

**Comment by JamesBotterill** [comment]
I thought as much thanks, right now it's perfect for my needs.
