### ISSUE TITLE
Add reduce

### ISSUE THREAD

**Issue by kelvinhammond** [TomPrograms/stormdb#8]
Add the `reduce` function for arrays or just subclass the Array class when applicable, keeping the `pointers` and other internal values in said class with extra methods.

**Comment by TomPrograms** [comment]
Do you think behaviour like the current .map() etc. is acceptable? .reduce() would reduce the array, return the StormDB instance and then on the .save() call rewrite the reduced list to the database.

**Comment by TomPrograms** [comment]
We could take two approaches here that can be integrated easily:

- Return the raw value of the reduced array
- Change the array in the database to the value of the reduced array and then return the StormDB object

Which do you think is preferable? Personally I'm leaning towards the second because that is the way `.map()` etc. have been integrated (with direct modification on the database).

**Comment by TomPrograms** [comment]
See #9 - PR containing `.reduce()` functionality following the second bullet point outlined above.
